### PR TITLE
Use Docusaurus

### PR DESCRIPTION
**Pull request by mdoryammilwalrus**
This PR includes

- Docusaurus
- Better Incognito file
- Update Ultraviolet-Node to Ultraviolet-App

> **Note**
> Using Docusaurus means you don't have to downgrade to a old version of NodeJS with security vulnerabilities.
>
> This has been tested with Firefox 108 and NodeJS 18.

### CODE REVIEW

**Comment by mdoryammilwalrus** [comment]
???

**Comment by QuiteAFancyEmerald** [comment]
epic lol sorry for the late reply

**Pull request merged**
